-- ============================================
-- INSERIMENTO RISORSE PER hrspecialistey@gmail.com
-- ============================================
-- Esegui questo script nel Supabase SQL Editor
-- ============================================

-- Inserisci le risorse con owner_email = 'hrspecialistey@gmail.com'
INSERT INTO risorse (nome, owner_email)
VALUES
  ('Abdel Rahman Mansour', 'hrspecialistey@gmail.com'),
  ('Adil Lamhaffad', 'hrspecialistey@gmail.com'),
  ('Adrian Rosca', 'hrspecialistey@gmail.com'),
  ('Agnes Marina', 'hrspecialistey@gmail.com'),
  ('Alaa Shoker', 'hrspecialistey@gmail.com'),
  ('Alam Rasal', 'hrspecialistey@gmail.com'),
  ('Alam Shaha', 'hrspecialistey@gmail.com'),
  ('Alessandro Amorena', 'hrspecialistey@gmail.com'),
  ('Alessandro Bellanti', 'hrspecialistey@gmail.com'),
  ('Alessandro Boni', 'hrspecialistey@gmail.com'),
  ('Alessandro Cavallotti', 'hrspecialistey@gmail.com'),
  ('Alessandro Itisuprabati', 'hrspecialistey@gmail.com'),
  ('Alessia Luppi', 'hrspecialistey@gmail.com'),
  ('Alessia Moncado', 'hrspecialistey@gmail.com'),
  ('Alessio Guidotti', 'hrspecialistey@gmail.com'),
  ('Alex Fiore', 'hrspecialistey@gmail.com'),
  ('Ali Youssef', 'hrspecialistey@gmail.com'),
  ('Allegra Vismara', 'hrspecialistey@gmail.com'),
  ('Anastasiya Irinyak', 'hrspecialistey@gmail.com'),
  ('Andrea Crespi', 'hrspecialistey@gmail.com'),
  ('Andrea Di Pietro', 'hrspecialistey@gmail.com'),
  ('Andrea Lorefice', 'hrspecialistey@gmail.com'),
  ('Andres Camargo', 'hrspecialistey@gmail.com'),
  ('Angelica Romano', 'hrspecialistey@gmail.com'),
  ('Angelo Costa', 'hrspecialistey@gmail.com'),
  ('Anis Aouidy', 'hrspecialistey@gmail.com'),
  ('Antonio Filoni', 'hrspecialistey@gmail.com'),
  ('Antonio Mazzotti', 'hrspecialistey@gmail.com'),
  ('Antony Carbone', 'hrspecialistey@gmail.com'),
  ('Aymane Meky', 'hrspecialistey@gmail.com'),
  ('Brayan Parvopasso', 'hrspecialistey@gmail.com'),
  ('Bruno Pantano', 'hrspecialistey@gmail.com'),
  ('Carlo Strada', 'hrspecialistey@gmail.com'),
  ('Caterina Betto', 'hrspecialistey@gmail.com'),
  ('Chiara Piccarolo', 'hrspecialistey@gmail.com'),
  ('Chiara Rocco', 'hrspecialistey@gmail.com'),
  ('Christian Giorrandello', 'hrspecialistey@gmail.com'),
  ('Clara Nicolosi', 'hrspecialistey@gmail.com'),
  ('Claudia Bonifacio', 'hrspecialistey@gmail.com'),
  ('Claudia Isoardi', 'hrspecialistey@gmail.com'),
  ('Cristian Canonico', 'hrspecialistey@gmail.com'),
  ('Dante Cascone', 'hrspecialistey@gmail.com'),
  ('David Baldoni', 'hrspecialistey@gmail.com'),
  ('David Zavala', 'hrspecialistey@gmail.com'),
  ('Davide Cristaldi', 'hrspecialistey@gmail.com'),
  ('Demetria Vasilitov', 'hrspecialistey@gmail.com'),
  ('Domenico Capizzi', 'hrspecialistey@gmail.com'),
  ('Eleonora Meschi', 'hrspecialistey@gmail.com'),
  ('Eni Xhaferaj', 'hrspecialistey@gmail.com'),
  ('Enrico Natale', 'hrspecialistey@gmail.com'),
  ('Eros Mangiacotti', 'hrspecialistey@gmail.com'),
  ('Eslam Mahmoud', 'hrspecialistey@gmail.com'),
  ('Evander Perez', 'hrspecialistey@gmail.com'),
  ('Fabio Clerici', 'hrspecialistey@gmail.com'),
  ('Fabio Lamanuzzi', 'hrspecialistey@gmail.com'),
  ('Mirjan Palushi', 'hrspecialistey@gmail.com'),
  ('Federica Cristiani', 'hrspecialistey@gmail.com'),
  ('Federica Scandella', 'hrspecialistey@gmail.com'),
  ('Federico Barbiero', 'hrspecialistey@gmail.com'),
  ('Federico Casamassima', 'hrspecialistey@gmail.com'),
  ('Federico Cesari', 'hrspecialistey@gmail.com'),
  ('Federico Lolli', 'hrspecialistey@gmail.com'),
  ('Filippo Rossi', 'hrspecialistey@gmail.com'),
  ('Francesco Antonini', 'hrspecialistey@gmail.com'),
  ('Francesco Luzzi', 'hrspecialistey@gmail.com'),
  ('Francesco Pellarin', 'hrspecialistey@gmail.com'),
  ('Franco Bonelli', 'hrspecialistey@gmail.com'),
  ('Franco Bonilla', 'hrspecialistey@gmail.com'),
  ('Gabriel Vozza', 'hrspecialistey@gmail.com'),
  ('Gaia Landoni', 'hrspecialistey@gmail.com'),
  ('Giacomo Donati', 'hrspecialistey@gmail.com'),
  ('Gianluigi Mosca', 'hrspecialistey@gmail.com'),
  ('Giorgio Sensi', 'hrspecialistey@gmail.com'),
  ('Giovanni Beccari', 'hrspecialistey@gmail.com'),
  ('Giovanni Dutto', 'hrspecialistey@gmail.com'),
  ('Giovanni Pellegrin', 'hrspecialistey@gmail.com'),
  ('Giovanni Tinelli', 'hrspecialistey@gmail.com'),
  ('Giulia Iarrera', 'hrspecialistey@gmail.com'),
  ('Giulia Senn', 'hrspecialistey@gmail.com'),
  ('Giulia Tripodi', 'hrspecialistey@gmail.com'),
  ('Giuliano Romano', 'hrspecialistey@gmail.com'),
  ('Hatim Kalali', 'hrspecialistey@gmail.com'),
  ('Ilaria Sabbatini', 'hrspecialistey@gmail.com'),
  ('Irene Simone', 'hrspecialistey@gmail.com'),
  ('Ismael Ramirez', 'hrspecialistey@gmail.com'),
  ('Islam Shorowar', 'hrspecialistey@gmail.com'),
  ('Jacqueline Sanchez', 'hrspecialistey@gmail.com'),
  ('Jair Valverde', 'hrspecialistey@gmail.com'),
  ('Jean Botros', 'hrspecialistey@gmail.com'),
  ('Josefina Neris', 'hrspecialistey@gmail.com'),
  ('Justine Gajiran', 'hrspecialistey@gmail.com'),
  ('Kevin Franco', 'hrspecialistey@gmail.com'),
  ('Kevin Martinez', 'hrspecialistey@gmail.com'),
  ('Khaled Abdel', 'hrspecialistey@gmail.com'),
  ('Kirollos Hanna', 'hrspecialistey@gmail.com'),
  ('Lamin Bojang', 'hrspecialistey@gmail.com'),
  ('Lavinia Popa', 'hrspecialistey@gmail.com'),
  ('Letizia Cernigliaro', 'hrspecialistey@gmail.com'),
  ('Liam Diop', 'hrspecialistey@gmail.com'),
  ('Lisa Magnus', 'hrspecialistey@gmail.com'),
  ('Loredana Rogato', 'hrspecialistey@gmail.com'),
  ('Lorenzo Valente', 'hrspecialistey@gmail.com'),
  ('Louay Ben', 'hrspecialistey@gmail.com'),
  ('Luca Assereto', 'hrspecialistey@gmail.com'),
  ('Luca Di Lella', 'hrspecialistey@gmail.com'),
  ('Luca Famà', 'hrspecialistey@gmail.com'),
  ('Luis Fernando', 'hrspecialistey@gmail.com'),
  ('Magdalena Tadini', 'hrspecialistey@gmail.com'),
  ('Mahmoud Mansour', 'hrspecialistey@gmail.com'),
  ('Manuel Basile', 'hrspecialistey@gmail.com'),
  ('Marco Raimondi', 'hrspecialistey@gmail.com'),
  ('Marco Silvestri', 'hrspecialistey@gmail.com'),
  ('Marco Tavernese', 'hrspecialistey@gmail.com'),
  ('Marco Zamboni', 'hrspecialistey@gmail.com'),
  ('Martina Anzalone', 'hrspecialistey@gmail.com'),
  ('Matteo Casara', 'hrspecialistey@gmail.com'),
  ('Matteo Raimondi', 'hrspecialistey@gmail.com'),
  ('Mattia Magri', 'hrspecialistey@gmail.com'),
  ('Mauro Ramos', 'hrspecialistey@gmail.com'),
  ('Micheal El Zeky', 'hrspecialistey@gmail.com'),
  ('Micheal Rocco', 'hrspecialistey@gmail.com'),
  ('Michele Di Rella', 'hrspecialistey@gmail.com'),
  ('Mikhail Fontana', 'hrspecialistey@gmail.com'),
  ('Mina Wazef', 'hrspecialistey@gmail.com'),
  ('Miriam Griffoni', 'hrspecialistey@gmail.com'),
  ('Misaele Bertone', 'hrspecialistey@gmail.com'),
  ('Monjurul Tanvir', 'hrspecialistey@gmail.com'),
  ('Nabil Talha', 'hrspecialistey@gmail.com'),
  ('Nadeszda Vlasova', 'hrspecialistey@gmail.com'),
  ('Nadia Talha', 'hrspecialistey@gmail.com'),
  ('Nelson', 'hrspecialistey@gmail.com'),
  ('Nelson Alvarez', 'hrspecialistey@gmail.com'),
  ('Nicolas Silva', 'hrspecialistey@gmail.com'),
  ('Nicolò Senn', 'hrspecialistey@gmail.com'),
  ('Nuwan Shanaka', 'hrspecialistey@gmail.com'),
  ('Olga Safonova', 'hrspecialistey@gmail.com'),
  ('Olivia Guala', 'hrspecialistey@gmail.com'),
  ('Omar Al Ghareeb', 'hrspecialistey@gmail.com'),
  ('Paolo Rotondo', 'hrspecialistey@gmail.com'),
  ('Pasquale Scotti', 'hrspecialistey@gmail.com'),
  ('Patricia Raicu', 'hrspecialistey@gmail.com'),
  ('Pietro Silva', 'hrspecialistey@gmail.com'),
  ('Pietro Sirtori', 'hrspecialistey@gmail.com'),
  ('Rayan Mozona', 'hrspecialistey@gmail.com'),
  ('Rayana Triunfo', 'hrspecialistey@gmail.com'),
  ('Riccardo Mazza', 'hrspecialistey@gmail.com'),
  ('Riccardo Giulio Cervi', 'hrspecialistey@gmail.com'),
  ('Riccardo Rossetto', 'hrspecialistey@gmail.com'),
  ('Rida Fahir', 'hrspecialistey@gmail.com'),
  ('Roberto Degioannis', 'hrspecialistey@gmail.com'),
  ('Roberto Oliviero', 'hrspecialistey@gmail.com'),
  ('Roberto Soria', 'hrspecialistey@gmail.com'),
  ('Ryan Zegnani', 'hrspecialistey@gmail.com'),
  ('Sabrina Rizzitano', 'hrspecialistey@gmail.com'),
  ('Sabrina Shoniia', 'hrspecialistey@gmail.com'),
  ('Said Massoudi', 'hrspecialistey@gmail.com'),
  ('Sajid Ali', 'hrspecialistey@gmail.com'),
  ('Samuel Mancuso', 'hrspecialistey@gmail.com'),
  ('Saphy Khanfar', 'hrspecialistey@gmail.com'),
  ('Sebastian Castro', 'hrspecialistey@gmail.com'),
  ('Sergio Aragon', 'hrspecialistey@gmail.com'),
  ('Shitiol Nursat', 'hrspecialistey@gmail.com'),
  ('Siavash Alinia', 'hrspecialistey@gmail.com'),
  ('Simone Tosi', 'hrspecialistey@gmail.com'),
  ('Sofia Alterni', 'hrspecialistey@gmail.com'),
  ('Soufiane El Aoufi', 'hrspecialistey@gmail.com'),
  ('Suhel Ahmed', 'hrspecialistey@gmail.com'),
  ('Tamiru Lo Verde', 'hrspecialistey@gmail.com'),
  ('Tariq Bamaaruf', 'hrspecialistey@gmail.com'),
  ('Teodora Alexa', 'hrspecialistey@gmail.com'),
  ('Tommaso Biondino', 'hrspecialistey@gmail.com'),
  ('Valentina Realini', 'hrspecialistey@gmail.com'),
  ('Valerio Zahariychuk', 'hrspecialistey@gmail.com'),
  ('Veronica Vigliotti', 'hrspecialistey@gmail.com'),
  ('Vicente Torres', 'hrspecialistey@gmail.com'),
  ('Yasin Abdelnaser', 'hrspecialistey@gmail.com'),
  ('Yazid Bachar', 'hrspecialistey@gmail.com'),
  ('Youssef Elmelegy', 'hrspecialistey@gmail.com'),
  ('Youssef Giorgis', 'hrspecialistey@gmail.com'),
  ('Youssef Mansour', 'hrspecialistey@gmail.com'),
  ('Youssef Nakhla', 'hrspecialistey@gmail.com'),
  ('Youssef Saleh', 'hrspecialistey@gmail.com'),
  ('Valeria Ramponi', 'hrspecialistey@gmail.com'),
  ('Domenico Amodeo', 'hrspecialistey@gmail.com'),
  ('Mattia Maestrelli', 'hrspecialistey@gmail.com'),
  ('Amine Raouf', 'hrspecialistey@gmail.com'),
  ('Nicolas Aidarbekov', 'hrspecialistey@gmail.com'),
  ('Zamanta Martinez', 'hrspecialistey@gmail.com'),
  ('Giacomo Carniello', 'hrspecialistey@gmail.com'),
  ('Massimiliano Clerici', 'hrspecialistey@gmail.com'),
  ('Mohamed El Hallaoui', 'hrspecialistey@gmail.com'),
  ('Omar Talat', 'hrspecialistey@gmail.com'),
  ('Olga Maksimenka', 'hrspecialistey@gmail.com'),
  ('Kevin Dahriu', 'hrspecialistey@gmail.com'),
  ('Riccardo Iannello', 'hrspecialistey@gmail.com'),
  ('Ricardo Pereira', 'hrspecialistey@gmail.com'),
  ('Alexandru Catichi', 'hrspecialistey@gmail.com'),
  ('Benedetta Barbera', 'hrspecialistey@gmail.com'),
  ('Sofia Angeli', 'hrspecialistey@gmail.com'),
  ('Wael Barasoom', 'hrspecialistey@gmail.com'),
  ('George Ciobanu', 'hrspecialistey@gmail.com'),
  ('Munaim Al Amran', 'hrspecialistey@gmail.com'),
  ('Marco Lucchini', 'hrspecialistey@gmail.com'),
  ('Maggie Bergamini', 'hrspecialistey@gmail.com'),
  ('Marta Nobili', 'hrspecialistey@gmail.com'),
  ('Nadia Tessari', 'hrspecialistey@gmail.com'),
  ('Riccardo Romano', 'hrspecialistey@gmail.com'),
  ('Filippo Gelmi', 'hrspecialistey@gmail.com'),
  ('Enrico Maria Valecchi', 'hrspecialistey@gmail.com'),
  ('Cosimo Imbrici', 'hrspecialistey@gmail.com'),
  ('Natali Cenka', 'hrspecialistey@gmail.com'),
  ('Omar Faruk', 'hrspecialistey@gmail.com'),
  ('Kavindu Jeevathmuni', 'hrspecialistey@gmail.com'),
  ('Noemi Balu', 'hrspecialistey@gmail.com'),
  ('Andrea Salerno', 'hrspecialistey@gmail.com'),
  ('Salvatore Amore', 'hrspecialistey@gmail.com'),
  ('Stefania Vescio', 'hrspecialistey@gmail.com'),
  ('Said Braccia', 'hrspecialistey@gmail.com'),
  ('Daniele Assereto', 'hrspecialistey@gmail.com'),
  ('Matteo Piccarolo', 'hrspecialistey@gmail.com'),
  ('Ina Chiriac', 'hrspecialistey@gmail.com'),
  ('Mattia De Giovanni', 'hrspecialistey@gmail.com'),
  ('Samiel Herdu', 'hrspecialistey@gmail.com'),
  ('Sara Bitto', 'hrspecialistey@gmail.com'),
  ('Bonny Basta', 'hrspecialistey@gmail.com'),
  ('Ahmed Abounagy', 'hrspecialistey@gmail.com'),
  ('Federico Baruffaldi', 'hrspecialistey@gmail.com'),
  ('Mattia Ventura', 'hrspecialistey@gmail.com'),
  ('Moreno Masucci', 'hrspecialistey@gmail.com'),
  ('Badar Fahoumi', 'hrspecialistey@gmail.com'),
  ('Abdelrahaman Ebrahim', 'hrspecialistey@gmail.com'),
  ('Crisitian Mancini', 'hrspecialistey@gmail.com'),
  ('Alessandro Lupi', 'hrspecialistey@gmail.com'),
  ('Ramez Hamed', 'hrspecialistey@gmail.com'),
  ('Yordy Cagua', 'hrspecialistey@gmail.com'),
  ('Alessandro Gargano', 'hrspecialistey@gmail.com'),
  ('Matteo Angeli', 'hrspecialistey@gmail.com'),
  ('Riccardo Pagni', 'hrspecialistey@gmail.com'),
  ('Naysha Rojas', 'hrspecialistey@gmail.com'),
  ('Mohamed Talha', 'hrspecialistey@gmail.com'),
  ('Davide Casu', 'hrspecialistey@gmail.com'),
  ('Jassim Aboudihaj', 'hrspecialistey@gmail.com'),
  ('Viviana Tallarita', 'hrspecialistey@gmail.com'),
  ('Floriana Donis', 'hrspecialistey@gmail.com'),
  ('Federico De Consoli', 'hrspecialistey@gmail.com'),
  ('Fiorenzo Patti', 'hrspecialistey@gmail.com'),
  ('Sahar Fathy', 'hrspecialistey@gmail.com'),
  ('Marco Raciti', 'hrspecialistey@gmail.com'),
  ('Fabio Franceschelli', 'hrspecialistey@gmail.com'),
  ('Greta Favorido', 'hrspecialistey@gmail.com'),
  ('Alexander Aina', 'hrspecialistey@gmail.com'),
  ('Lorenzo Intrigliolo', 'hrspecialistey@gmail.com'),
  ('Ciro Russo', 'hrspecialistey@gmail.com'),
  ('Meggie Hoxha', 'hrspecialistey@gmail.com'),
  ('Beatrice Allegretti', 'hrspecialistey@gmail.com'),
  ('David Muhunga', 'hrspecialistey@gmail.com'),
  ('Giuseppe Rivezzi', 'hrspecialistey@gmail.com'),
  ('Yannick Kuimo', 'hrspecialistey@gmail.com'),
  ('Brayan Mattiello', 'hrspecialistey@gmail.com'),
  ('Camilla Cicconi', 'hrspecialistey@gmail.com'),
  ('Anna De Bin', 'hrspecialistey@gmail.com'),
  ('Manvir Singh', 'hrspecialistey@gmail.com'),
  ('Valentina Ramos', 'hrspecialistey@gmail.com'),
  ('Annalisa Quaggia', 'hrspecialistey@gmail.com'),
  ('Johny Kassis', 'hrspecialistey@gmail.com'),
  ('Sara Mohamed', 'hrspecialistey@gmail.com'),
  ('Mimmo Azzam', 'hrspecialistey@gmail.com'),
  ('Katja Musovich', 'hrspecialistey@gmail.com'),
  ('Gianmaria Boero', 'hrspecialistey@gmail.com'),
  ('Youssef Abdelmalak', 'hrspecialistey@gmail.com'),
  ('Armel Londo', 'hrspecialistey@gmail.com'),
  ('Antonio Matta', 'hrspecialistey@gmail.com'),
  ('Ayoub Mehrar', 'hrspecialistey@gmail.com'),
  ('Federico Palumbo', 'hrspecialistey@gmail.com'),
  ('Sofia Leone', 'hrspecialistey@gmail.com'),
  ('Massimo Rizzo', 'hrspecialistey@gmail.com'),
  ('Giuliana Bumbu', 'hrspecialistey@gmail.com'),
  ('Stefano Sensolo', 'hrspecialistey@gmail.com'),
  ('Roberta Tasca', 'hrspecialistey@gmail.com'),
  ('Marin Paloka', 'hrspecialistey@gmail.com'),
  ('Dean Legname', 'hrspecialistey@gmail.com'),
  ('Pellegrino Morcone', 'hrspecialistey@gmail.com'),
  ('Eugenia Esposito', 'hrspecialistey@gmail.com'),
  ('Michele Dargenio', 'hrspecialistey@gmail.com'),
  ('David Lagos', 'hrspecialistey@gmail.com'),
  ('Julio Montero', 'hrspecialistey@gmail.com'),
  ('Luca Pasquali', 'hrspecialistey@gmail.com'),
  ('William Henriquez', 'hrspecialistey@gmail.com'),
  ('Maneth Kerewgodage', 'hrspecialistey@gmail.com'),
  ('Amadou Sakho', 'hrspecialistey@gmail.com'),
  ('Amin Errahouly', 'hrspecialistey@gmail.com'),
  ('Tomas Biancacci', 'hrspecialistey@gmail.com'),
  ('Alessandro Matà', 'hrspecialistey@gmail.com'),
  ('Nicoleta Stancu', 'hrspecialistey@gmail.com'),
  ('Giuseppe Alava', 'hrspecialistey@gmail.com'),
  ('Giordano Bortolussi', 'hrspecialistey@gmail.com'),
  ('Irisild Islamaj', 'hrspecialistey@gmail.com'),
  ('Andrea Zanaboni', 'hrspecialistey@gmail.com'),
  ('Maxwell Brajdic', 'hrspecialistey@gmail.com'),
  ('Jennifer Salvador', 'hrspecialistey@gmail.com'),
  ('Julien Grande', 'hrspecialistey@gmail.com'),
  ('Giacomo De Petri', 'hrspecialistey@gmail.com'),
  ('Davide Ruju', 'hrspecialistey@gmail.com'),
  ('Micheal Morales', 'hrspecialistey@gmail.com'),
  ('Steeven Javier', 'hrspecialistey@gmail.com'),
  ('Lorenzo Ammenola', 'hrspecialistey@gmail.com'),
  ('Oscar Romero', 'hrspecialistey@gmail.com'),
  ('Samuel Zaka', 'hrspecialistey@gmail.com'),
  ('Valentina Gusmitta', 'hrspecialistey@gmail.com'),
  ('Bianca De Bellis', 'hrspecialistey@gmail.com'),
  ('Daniela Daku', 'hrspecialistey@gmail.com'),
  ('Marina Michelsanti', 'hrspecialistey@gmail.com'),
  ('Tarek Abul', 'hrspecialistey@gmail.com'),
  ('Giorgio Ghity', 'hrspecialistey@gmail.com'),
  ('William Tuscano', 'hrspecialistey@gmail.com'),
  ('Antonio Corigliano', 'hrspecialistey@gmail.com'),
  ('Shevin Poddala', 'hrspecialistey@gmail.com'),
  ('Emanuele Chessa', 'hrspecialistey@gmail.com'),
  ('Victor Ortega', 'hrspecialistey@gmail.com'),
  ('Rakib Hasan', 'hrspecialistey@gmail.com'),
  ('Rajaa Khair', 'hrspecialistey@gmail.com'),
  ('Jason Tekle', 'hrspecialistey@gmail.com'),
  ('Filippo Saad', 'hrspecialistey@gmail.com')
ON CONFLICT (nome) DO UPDATE SET
  owner_email = EXCLUDED.owner_email,
  updated_at = NOW();

-- Verifica le risorse inserite
SELECT 
  nome,
  owner_email
FROM risorse 
WHERE owner_email = 'hrspecialistey@gmail.com'
ORDER BY nome;

-- Conta le risorse inserite
SELECT COUNT(*) as totale_risorse 
FROM risorse 
WHERE owner_email = 'hrspecialistey@gmail.com';

